### ISSUE TITLE
Installation via custom ISO fails during deployment step

### ISSUE THREAD

**Issue by DocKDE** [blue-build/template#19]
Hi, I just started migrating my startingpoint builds over to blue-build. I haven't really changed anything but created new cosign keys. The builds work fine, an ISO is generated and I downloaded it to try installing it. After going through all the options int he installer and starting the installation process this throws the following error:
```
The following error occurred while installing the payload. This is a fatal error and installation will be aborted.

The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=ghcr.io/dockde/bluejay-next:latest --no-signature-verification' exited with the code 1.
```

I haven't seen this before and would appreciate help. If this is not the best place to report this, I'd be happy for pointers for where else to go.

**Comment by xynydev** [comment]
Universal Blue is deprecating the old ISO functionality due to numerous, which is unfortunately still in the template. It should probably be removed. I suggest generating an offline ISO locally instead. This can't be done on GitHub, because the file size would be too big for releases.

https://blue-build.org/learn/universal-blue/#fresh-install-from-an-iso

**Comment by DocKDE** [comment]
Oh, I see! Didn't realize this but I'm gonna go and try that route then.Thanks for the quick response!
