### ISSUE TITLE
[BUG] Installation of nerd fonts does not work

### ISSUE THREAD

**Issue by RVSmooth** [blue-build/template#44]
As the title suggests, nerd-fonts module does not seem to work.
I tested installing JetBrainsMono and other two but it does not work.
i.e., the fonts do not get installed

https://github.com/RVSmooth/AllBlue/actions/runs/12154254900/job/33893721674#step:2:2584

### Tested on
- Bluefin image 
- Ublue-main image

**Comment by xynydev** [comment]
There was a recent issue with the fonts module, which was filed under the correct repo here: https://github.com/blue-build/modules/issues/371

It was also promptly fixed by fiftydinar six hours ago, and should work now.

It looks like your build is not actually running the fonts module again, but running adding a version of the layer from GitHub cache; likely one where the module failed to do anything. To invalidate the GitHub cache you can make changes to your `fonts` module configuration, or to anything before it in your recipe. The cache should also invalidate automatically after a while, so tomorrow's builds should have the `fonts` module working again. 

Feel free to comment on https://github.com/blue-build/modules/issues/371 if the fonts module does not start working again.

**Comment by RVSmooth** [comment]
Thanks for the reply. And sorry I couldn't think of the issues of modules being at a separate repo and created another issue.

> There was a recent issue with the fonts module, which was filed under the correct repo here: [blue-build/modules#371](https://github.com/blue-build/modules/issues/371)
> 
> It was also promptly fixed by fiftydinar six hours ago, and should work now.
that's really cool

> It looks like your build is not actually running the fonts module again, but running adding a version of the layer from GitHub cache; likely one where the module failed to do anything. To invalidate the GitHub cache you can make changes to your `fonts` module configuration, or to anything before it in your recipe. The cache should also invalidate automatically after a while, so tomorrow's builds should have the `fonts` module working again.
Alright I will try it again.
> Feel free to comment on [blue-build/modules#371](https://github.com/blue-build/modules/issues/371) if the fonts module does not start working again.
